
import random


text='''
This is a multiuser game.
In this game, a number (1,100) is randomly generated by computer. You have to guess that number. 
The player who will guess the number in least number of guesses, will be the winner and other positions will be decided in the same way.

There are 3 levels of game ->

        1 (Easy) (Here very close means difference is 5)
        2 (Medium) (Here very close means difference is 10)
        3 (Hard) (Here very close means difference is 15)
        
To left the game, Press 0.

Players should not be same. Otherwise it will be considered as single player.

'''
print(text)

level_of_game=int(input('Enter the Level of game (1,2,3): '))

print('\n')
number_of_players=int(input('Enter the no. of players: '))
print('\n')
players={}

players_input=list()

for i in range(number_of_players):
    player=input(f'Enter name of player {i+1} : ')
    players[player]=list()


for player in players.keys():
    random_number=random.randrange(1,101)
    print('\n')
    print(f'{player}\'s turn: ')
    print('\n')
    user_input=-1;
    while(random_number!=user_input):
        user_input=int(input('Guess the number: '))
        
        players[player].append(user_input)
        if(user_input==0):
            print('You left the game.')
            players[player].clear()
            players[player].append(-1)
            break
        elif user_input==random_number:
            break
        elif(abs(user_input-random_number)<=5*level_of_game):
            print('Very close to the number.')
        elif(random_number>user_input):
            print('Choose a large number')
        else:
            print('Choose a small number.')
            



players_data_list=list(players.items())

players_data_list.sort(key=lambda player:len(player[1]))



steps=list()

[steps.append(len(step[1])) for step in players_data_list]


pos=1;
print('\n')
print('Position of the Players:')
print('\n')
for index in range(len(players_data_list)):
    if index==0:
        print(f'Position {pos} {players_data_list[index][0]} Total steps -> {len(players_data_list[index][1])} steps')
    else:
        if steps[index]==steps[index-1]:
            print(f'Position {pos} {players_data_list[index][0]} Total steps -> {len(players_data_list[index][1])} steps')
        else:
            pos+=1;
            print(f'Position {pos} {players_data_list[index][0]} Total steps -> {len(players_data_list[index][1])} steps')
            
print('\n')